// src/redux/actions/types.js

export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const ADD_GAME_REQUEST = 'ADD_GAME_REQUEST';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';

export const UPDATE_GAME_PARTICIPANTS_REQUEST = 'UPDATE_GAME_PARTICIPANTS_REQUEST';
export const UPDATE_GAME_PARTICIPANTS_SUCCESS = 'UPDATE_GAME_PARTICIPANTS_SUCCESS';
export const UPDATE_GAME_PARTICIPANTS_FAILURE = 'UPDATE_GAME_PARTICIPANTS_FAILURE';

export const DELETE_GAME_REQUEST = 'DELETE_GAME_REQUEST';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';

// Add the following lines
export const PURCHASE_GAME_REQUEST = 'PURCHASE_GAME_REQUEST';
export const PURCHASE_GAME_SUCCESS = 'PURCHASE_GAME_SUCCESS';
export const PURCHASE_GAME_FAILURE = 'PURCHASE_GAME_FAILURE';
